version: '2'
services: 
  mysql:
    image: otavio/mysql
    container_name: otavio-mysql
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
